
services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "ChilliSauce123@"]

  redis-commander:
    image: rediscommander/redis-commander:latest
    platform: linux/amd64
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_PASSWORD=ChilliSauce123@
      - HTTP_USER=ReEf
      - HTTP_PASSWORD=qwerty123aA@
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert.pem:/etc/nginx/certs/cert.pem
      - ./nginx/key.pem:/etc/nginx/certs/key.pem
    depends_on:
      - redis-commander
    restart: always

volumes:
  redis-data:
