version: '3.8'

services:
  redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_PASSWORD=strongpassword123
      - HTTP_USER=ReEf
      - HTTP_PASSWORD=qwerty123aA@
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert.pem:/etc/nginx/certs/cert.pem
      - ./nginx/key.pem:/etc/nginx/certs/key.pem
    depends_on:
      - redis-commander
    restart: always

volumes:
  redis-data:
