version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/redis-stack.conf
    command: ["redis-server", "/redis-stack.conf"]

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    environment:
      RI_HOST: 0.0.0.0
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/data
    restart: always
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert.pem:/etc/nginx/certs/cert.pem
      - ./nginx/key.pem:/etc/nginx/certs/key.pem
    depends_on:
      - redisinsight
    restart: always

volumes:
  redis-data:
  redisinsight-data:
