services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "ChilliSauce123@", "--bind", "0.0.0.0", "--protected-mode", "no"]
    volumes:
      - redis-data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    environment:
      RI_APP_PORT: 5540
      RI_APP_HOST: 0.0.0.0
      RI_PROXY_PATH: /redis-dashboard
      RI_REDIS_HOST: redis
      RI_REDIS_PORT: 6379
      RI_REDIS_PASSWORD: ChilliSauce123@
      RI_REDIS_ALIAS: "Reef Redis Server"
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/data
    restart: always
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert.pem:/etc/nginx/certs/cert.pem
      - ./nginx/key.pem:/etc/nginx/certs/key.pem
    depends_on:
      - redisinsight
    restart: always

volumes:
  redis-data:
  redisinsight-data: